name: Build

on:
  push:
    branches: [ github-actions ]
  workflow_dispatch:

jobs:
  build_all_packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and install Arch Linux's SELinux support packages in a docker container
        run: docker build -t arch-selinux-build .
      - name: Run the container - built packages are transferred to build host
        run: docker run -v "$(pwd)/pkgs:/packages" --rm arch-selinux-build
      - name: Upload packages as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Arch Linux packages for SELinux support
          path: pkgs
